### PR TITLE
Dropbox API v2 upgrade

### LINKED ISSUE #2: Switch to Dropbox API v2
Hi,

I've just followed the installation process, and it appears that V1 of the DropBox API was decommissioned in October 2017.  Do you have any planned updates.  As for now, this code returns:

v1_retired

Many Thanks, Tom

### PR DESCRIPTION
**Pull request by drobee**
Closes #2

### CODE REVIEW

**Comment by mre** [comment]
Ah wonderful. Thank you very much for that @drobee. ❤️

**Comment by mre** [comment]
Are you participating in this years [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?
If you sign up, this will for sure count as a contribution there. Dunno what happens if I merge that before you sign up, so just wanted to be sure.

**Comment by drobee** [comment]
Yep, that’s how i found this repo 🙂 Thanks!

**Comment by mre** [comment]
I'm confused. Was the repo announced somewhere? 😅

**Comment by drobee** [comment]
I’ve searched for open issues in repositories and i liked yours 😉

**Pull request merged**
